export {
  HEALTH_CATEGORIES,
  HEALTH_CONFIDENCE,
  HEALTH_RECORD_SCHEMA,
  HEALTH_SEVERITIES,
  HEALTH_STATUSES,
  adaptContextUsageEvidence,
  adaptLifecycleReceiptEvidence,
  adaptOccupantModelEvidence,
  adaptQueueTransitionEvidence,
  adaptTopologyActivityEvidence,
  adaptWatchdogHistoryEvidence,
  adaptWorkGraphEvidence,
  boundHealthEvidence,
  canonicalHealthJson,
  deriveHealthSourceFreshness,
  healthEpisodeId,
  projectHealthRecord,
  type BoundedHealthEvidence,
  type HealthCategory,
  type HealthConfidence,
  type HealthEvidenceReference,
  type HealthFreshnessState,
  type HealthQueryBounds,
  type HealthRecord,
  type HealthRecordDraft,
  type HealthScope,
  type HealthSeverity,
  type HealthSourceFreshness,
  type HealthStatus,
} from "./domain/health-projection.js";
export type { OperatingPosture, OperatingContext } from "./domain/rig-mode/operating-posture.js";
